Repository JECT-Study/PetFit-3rd-FE, pull requests merged in 2025-07, with the labels that each got.

#18 feat: 슬롯 UI 구현 (KB3-76)
  src/assets/icons/meal.svg
  src/assets/icons/poop.svg
  src/assets/icons/skin.svg
  src/assets/icons/teeth.svg
  src/assets/icons/walk.svg
  src/assets/icons/water.svg
  src/constants/slot.ts
  src/features/slot/SlotButton.tsx
  src/features/slot/SlotInput.tsx
  src/pages/SlotSettingPage.tsx
  src/routes/Router.tsx
Labels: ✨feature

#20 feat: 회원가입 시 반려동물 사전 정보 입력 페이지 구현 (KB3-48)
  package-lock.json
  package.json
  src/components/CustomDatePicker.tsx
  src/components/CustomSelect.tsx
  src/components/PetRegisterForm.tsx
  src/pages/LoginPage.tsx
  src/pages/SignupPetRegisterPage.tsx
  src/routes/Router.tsx
  src/types/common.ts
  src/utils/petNameValidation.ts
Labels: ✨feature

#27 feat: 홈화면 일정, 특이사항 조회 UI 구현
  src/features/home/BriefCard.tsx
  src/features/home/NameTagBar.tsx
  src/features/home/TodayBar.tsx
  src/mocks/homeData.ts
  src/pages/HomePage.tsx
Labels: ✨feature

#32 feat: 일정 알림 등록 기능 구현 (KB3-52)
  src/components/common/ConfirmDeleteModal.tsx
  src/components/common/DeleteModal.tsx
  src/components/common/FormInput.tsx
  src/components/common/FormTextarea.tsx
  src/components/common/MoreActionDropdown.tsx
  src/features/alarm/ScheduleAlarmItem.tsx
  src/features/alarm/ScheduleRegisterModal.tsx
  src/pages/AlarmPage.tsx
  src/routes/Router.tsx
  src/types/alarm.ts
  src/utils/alarmValidation.ts
Labels: ✨feature

#36 feat: 날짜 관리 타입 변경 및 주간 달력에서 특이사항 추가/수정/삭제 기능 구현 (KB3-83)
  src/assets/icons/bird.svg
  src/assets/icons/cat.svg
  src/assets/icons/dog.svg
  src/assets/icons/fish.svg
  src/assets/icons/hamster.svg
  src/assets/icons/lizard.svg
  src/components/CustomDatePicker.tsx
  src/components/common/FormTextarea.tsx
  src/components/common/MoreActionDropdown.tsx
  src/constants/calendar.ts
  src/features/alarm/ScheduleAlarmItem.tsx
  src/features/alarm/ScheduleRegisterModal.tsx
  src/features/calendar/MonthView.tsx
  src/features/calendar/MonthlyViewPanel.tsx
  src/features/calendar/NoteItem.tsx
  src/features/calendar/NoteItemList.tsx
  src/features/calendar/NoteModal.tsx
  src/features/calendar/WeekView.tsx
  src/features/calendar/WeeklyDetailsSection.tsx
  src/features/calendar/WeeklyViewPanel.tsx
  src/mocks/calendarData.ts
  src/pages/AlarmPage.tsx
  src/pages/CalendarPage.tsx
  src/pages/SignupPetRegisterPage.tsx
  src/types/alarm.ts
  src/types/calendar.ts
  src/types/form.ts
  src/types/note.ts
  src/utils/calendar.ts
  src/utils/validators.ts
Labels: ✨feature, 👩🏻‍💻frontend, 🪄refactor

#42 chore: 카카오 로그인 배포 환경 대응 설정 (KB3-94)
  .gitignore
  src/apis/auth.ts
  src/apis/axiosInstance.ts
  src/pages/AuthRedirectPage.tsx
  src/pages/HomePage.tsx
  src/pages/SignupPetRegisterPage.tsx
  src/routes/Router.tsx
Labels: ⚙️chore

#44 hotfix: 카카오 인증 후 리디렉션 시 쿠키 설정 API 호출 처리 (KB3-95)
  src/apis/auth.ts
  src/apis/axiosInstance.ts
  src/constants/env.ts
  src/main.tsx
  src/pages/AuthRedirectPage.tsx
  src/pages/TokenRedirectPage.tsx
  src/routes/PrivateRouter.tsx
  src/routes/Router.tsx
  src/store/authSlice.ts
  src/store/store.ts
Labels: ⚙️chore, 🐛bug, 👨🏻‍💻backend

#48 feat: 개발환경 로그인 리디렉션 수정 및 일정 CRUD API 연동
  src/apis/alarm.ts
  src/apis/auth.ts
  src/components/CustomDatePicker.tsx
  src/components/PetRegisterForm.tsx
  src/pages/AlarmPage.tsx
  src/pages/AuthRedirectPage.tsx
  src/pages/SignupPetRegisterPage.tsx
  src/routes/Router.tsx
  src/store/petSlice.ts
  src/utils/transform/alarm.ts
Labels: ✨feature

#50 feat: 반려동물 정보 등록 API 연동 및 일정 API 연동 마무리 (KB3-98)
  src/App.tsx
  src/apis/alarm.ts
  src/apis/pets.ts
  src/features/alarm/ScheduleRegisterModal.tsx
  src/hooks/useRegisterPet.ts
  src/pages/AlarmPage.tsx
  src/pages/HomePage.tsx
  src/pages/SignupPetRegisterPage.tsx
  src/store/petSlice.ts
  src/store/store.ts
  src/types/form.ts
  src/utils/transform/alarm.ts
Labels: ✨feature
